linters:
  enable:
    - gofumpt
    - thelper
    - goimports
    - tparallel
    - wastedassign
    - unparam
    - prealloc
    - unconvert
    - exhaustive
    - makezero
    - nakedret
  fast: false

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  nakedret:
    max-func-lines: 0

run:
  timeout: 10m

issues:
  exclude-dirs-use-default: true
  exclude-dirs:
    - vendor