# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto

builds:
  - id: binary
    goos:
      # - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease
  - id: snap
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=snap
  - id: deb
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=deb

archives:
  - builds:
      - binary
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: x86
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
  - builds:
      - deb
    format: deb

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bump"

brews:
  - tap:
      owner: jesseduffield
      name: homebrew-lazydocker

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/jesseduffield/lazydocker/"

    # Your app's description.
    # Default is empty.
    description: "A simple terminal UI for docker, written in Go"

nfpms:
  - id: deb
    package_name: lazydocker
    license: MIT
    maintainer: "Jesse Duffield <jesse@duffield.com>"
    vendor: "Jesse Duffield"
    homepage: "https://github.com/jesseduffield/lazydocker"
    description: "A simple terminal UI for docker, written in Go"
    formats:
      - deb
    dependencies:
      - docker
      - docker-compose

snapcrafts:
  - name: lazydocker
    summary: A simple terminal UI for docker, written in Go
    description: A simple terminal UI for docker, written in Go
    confinement: strict
    grade: stable
    apps:
      lazydocker:
        command: lazydocker
        plugs:
          - network
          - network-bind
          - docker
    parts:
      lazydocker:
        source: .
        plugin: go
        go-importpath: github.com/jesseduffield/lazydocker
        build-snaps:
          - go
        build-packages:
          - git
